# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxCKm0lyZVDyofrLZjN2k7oQ3kqUd-ga

TOPIC: Python Basics Variable

"1. Declare two variables, `x` and `y`, and assign them integer values. Swap the
values of these variables without using any temporary variable
"""

#Taking user input to store the value of two variables
x= int(input("Enter the value of x : "))
y= int(input("Enter the value of y : "))
# Print the original values
print("Original values: x =", x, ", y =", y)

# Swap values without using a temporary variable
x = x + y
y = x - y
x = x - y

# Print the swapped values
print("Swapped values: x =", x, ", y =", y)

"""2. Create a program that calculates the area of a rectangle. Take the length and
width as inputs from the user and store them in variables. Calculate and
display the area."""

length = float(input("Enter the length of the rectangle:"))
breadth = float(input("Enter the breadth of the rectangle:"))

area= length*breadth
print("The area of the rectangle is : ", area)

"""3. Write a Python program that converts temperatures from Celsius to
Fahrenheit. Take the temperature in Celsius as input, store it in a variable,
convert it to Fahrenheit, and display the result."""

# Take temperature in Celsius as input
celsius_temperature = float(input("Enter temperature in Celsius: "))

# Convert Celsius to Fahrenheit
fahrenheit_temperature = (celsius_temperature * 9/5) + 32

# Display the result
print(f"{celsius_temperature} degrees Celsius is equal to {fahrenheit_temperature} degrees Fahrenheit.")

"""TOPIC: String Based Questions

1. Write a Python program that takes a string as input and prints the length of
the string."
"""

str1=input("Enter the string: ")
print("The length of the string is : ", len(str1))

"""2. Create a program that takes a sentence from the user and counts the number
of vowels (a, e, i, o, u) in the string."""



Str1 = input(" Enter the string: ")
cntr=0
for i in Str1:
  if i=='a':
    cntr+=1
  if i=='e':
    cntr+=1
  if i=='i':
    cntr+=1
  if i=='o':
    cntr+=1
  if i=='u':
    cntr+=1

print("The number of vowels: ",cntr)

"""3. Given a string, reverse the order of characters using string slicing and print
the reversed string."""

original_string = input("Enter the string that needs to be reversed: ")
reversed_string = original_string[::-1]

print(reversed_string)

"""4. Write a program that takes a string as input and checks if it is a palindrome
(reads the same forwards and backwards)."""

original_string = input("Enter the string that needs to be reversed: ")
reversed_string = original_string[::-1]

if original_string==reversed_string:
  print("It is a pallindrome")

"""Create a program that takes a string as input and removes all the spaces from
it. Print the modified string without spaces."""

out_str=""
inp_str=input("Enter the string: ")
for i in inp_str:
  if i==" ":
    continue
  else:
    out_str=out_str+i
print("output string without spaces: ",out_str)

